### ISSUE TITLE
Running first test for get all images endpoint

### ISSUE THREAD

**Issue by meganluisa** [meganluisa/experiences-app#3]
Hey @lizziegooding 

I am trying to get at least one test working in my "experiences app" project, so I started by testing that an array of objects is returned from hitting the "get/images" endpoint. This endpoint is meant to return a JSON of all images in the database. 

You can look at how I do this [in my code](https://github.com/meganluisa/experiences-app/blob/test-code/experiences-app-backend/__tests__/routes.test.js), line 15. I got the idea to use [arrayContaining](https://jestjs.io/docs/expect#expectarraycontainingarray) from a tutorial. 

The test doesn't work, because I can't seem to hit the endpoint (app.get(api/images)) correctly in my test file. I'm perhaps not importing something right, or am misunderstanding something. Regardless, while I debug this test file myself, I wanted to share the code with you and give you a general idea of the test I am trying to run. You may tell me it's a very unhelpful/useless test to run and I can then switch gears to test something else.

Let me know if you have any questions

**Comment by lizziegooding** [comment]
👋  A couple of thoughts to get you started:

- be careful of how you're defining the route you want to test here; you need to add a backslash before the beginning of the route to have it match how you've defined your route in your express server (`/api/images` rather than `api/images`)
https://github.com/meganluisa/experiences-app/blob/f4829a3cacaf5953e61b4e0704666db0a733fceb/experiences-app-backend/__tests__/routes.test.js#L12 
- You've successfully used supertest to help test your express app and it's working great 🎉  the problem is your tests are still hanging because you haven't mocked everything your route does. You also need to mock the `Photo.find` function. I would suggest looking at how jest supports mocking entire modules in order to mock you `models/photo` module and then decide what kind of fake implementation you want to create for what fake photos it'll return (check out jest's `mockImplementation` or `mockResolvedValue` functions)

**Comment by meganluisa** [comment]
Remember last year when I was first writing the route, I ran into a bug, so we debugged on one of our calls and it ended up being a slash missing at the end of the path? :')
